### ISSUE TITLE
No menu item in Xcode 8.0 (8A218a)

### ISSUE THREAD

**Issue by popizdeh** [mapbox/XcodeClangFormat#1] opened 2016-09-14 23:22 UTC
Is this supposed to be installed somehow? I have XcodeClangFormat running, I open Xcode and there's no entry in the Editor menu.

**Comment by Slyv** [comment] 2016-09-15 06:53
I have the same problem.

**Comment by kkaefer** [comment] 2016-09-15 14:37
On OS X 10.11, you'll need to run `sudo /usr/libexec/xpccachectl`, then **reboot**. On macOS Sierra, they should be loaded by default. Please reopen if you don't see the menu item.

**Comment by popizdeh** [comment] 2016-09-15 23:08
That didn't help :(

**Comment by Slyv** [comment] 2016-09-16 07:40
Didn't help.

**Comment by jehnes** [comment] 2016-09-19 03:47
I had the same problem, did run sudo /usr/libexec/xpccachectl and restarted twice, still the same. 

What finally did the trick:

In the Xcode project select the clang-format (the extension) target and then edit the scheme ( Product > Scheme > Edit Scheme ... ). In the Info tab of the Run settings set Xcode as the Executable. (By choosing Other... you can browse for the Xcode application on your file system).

Then, when you press the build and run button, a new Xcode application will start up. (After a short while its icon will turn black) The menu item will be available in that Xcode app. 

After closing this Xcode and restarting the Xcode you were running before, the normal (blue icon) Xcode will have the clang-format entry in the Editor menu as well.

**Comment by popizdeh** [comment] 2016-09-20 00:55
@jehnes "In the Xcode project select the clang-format", what project are you referring to?

**Comment by jehnes** [comment] 2016-09-21 04:29
I meant the XcodeClangFormat project, the project this discussion is about. You can download it from github. It has two targets, one is an executable that when run lets you select a style or custom .clang-format file, the other is the extension. It is called clang-format. This is the target for which you may have to edit the Scheme.

**Comment by zinuzoid** [comment] 2016-09-21 06:21
I have same problem. And still not fixed after run `sudo /usr/libexec/xpccachectl` and reboot my macbook. Also try restart xcode, plugin several times.

**Comment by Slyv** [comment] 2016-09-21 08:29
@jehnes solutions works! However after quitting Xcode (all instances) clang-format menu item disappears, and i have to run XcodeClangFormat project again.

**Comment by kkaefer** [comment] 2016-09-21 11:07
I could reproduce this issue on El Capitan with Xcode 8, but I was unable to find a better solution than cloning this repository and following the steps for [building this extension](https://github.com/mapbox/XcodeClangFormat#building)

**Comment by Slyv** [comment] 2016-09-21 12:03
I have now macOS Sierra, but nothing changed. @jehnes solution still works, but menu item disappears after Xcode quit and i have to run XcodeClangFormat again.

**Comment by libo19931030** [comment] 2016-09-21 12:04
could you please give a clear example to show how to install, what you said make me confused...

**Comment by Slyv** [comment] 2016-09-21 12:09
@libo19931030 For clang-format target set Executable to "Xcode.app" (select Other... and find Xcode in Applications). 
![xcode_clang](https://cloud.githubusercontent.com/assets/763309/18710306/cea38a3c-8004-11e6-9a35-5384d10825ec.png)

**Comment by jehnes** [comment] 2016-09-26 05:35
Hmm, not sure why the menu item disappears after Xcode is quit for you guys. In my case it did get installed and remains there after restarting Xcode also after rebooting it is still there. Not sure what may have made it stick for me that doesn't work for you.

I assume you have an editor open in Xcode when you look for the menu item, right? Because it will only appear when you have a source editor open. So, for example if you are looking at a storyboard in interface builder (or no project has been opened yet) it will not be there.

**Comment by ollitapa** [comment] 2016-09-26 05:39
I needed to manually enable the extension from System Preferences -> Extensions -> Put a checkmark to XcodeClangFormat
<img width="663" alt="screen shot 2016-09-26 at 8 38 14" src="https://cloud.githubusercontent.com/assets/4511526/18823654/a75067d4-83c4-11e6-9ccb-675370e8d826.png">

**Comment by Slyv** [comment] 2016-09-26 07:57
@ollitapa - Thanks, it helped!

**Comment by kkaefer** [comment] 2016-09-26 08:20
@ollitapa thanks for the hint! I added it to the readme. It looks like the *Xcode Source Editor* section isn't available on OS X 10.11, so for the time being, the only way to run this extension seems to be to build it manually with Xcode.

**Comment by jehnes** [comment] 2016-09-27 02:50
Ok, this is getting bizarre: I upgraded to Sierra yesterday and after that the menu entry was gone. Never mind. So I did the same thing as before (selected Xcode as the executable in the Scheme for the clang-format target) and when the Xcode with the blackened icon started up the menu idem was there and I also saw XcodeClangFormat show up in the extensions preferences as @ollitapa posted. But as soon as I quit the blackened Xcode, it disappeared from the extensions preferences and also did not appear again in newly started instances of Xcode.

However! Later, when I was trying it again and for some reason the blackened Xcode (and maybe also the Xcode that started it) got stuck and I needed to force quit them. When the blackened Xcode was force quit, the XcodeClangFormat did NOT disappear from the Extensions preferences and it is now permanently installed and as a consequence the menu item is now always available in Xcode whenever an editor is open. 

So, if you still cannot get the extension to stick around after quitting the Xcode with the blackened icon I suggest that you try to force quit this Xcode (and possibly the Xcode that started it). In fact it may be enough to kill the blackened Xcode by pressing the stop button in the Xcode that started it.

I hope that helps...

**Comment by kkaefer** [comment] 2016-09-27 08:26
@jehnes it's likely that this is a bug on the Xcode side; I'm unsure about what else I could do to make the extension stay in the menu.

**Comment by jehnes** [comment] 2016-09-28 09:58
@kkaefer Yes, I'm sure it is Xcode or macOS related. It was not my intention to imply that it was your fault. I just thought I let all of you know of this odd behaviour of how the extension eventually got to stick around. 

I assume that when you use Xcode to test extensions it installs the extension, then runs the executable that uses the extension (in this case Xcode with the black icon) and when finished it removes the extension again in order to prevent possibly faulty extensions to hang around in the system. But when I had to force quit Xcode, that removal step did not happen. 
In fact I was able to reproduce this several times. I just rerun the app extension from Xcode and when I ended the black icon Xcode the extension disappeared from the Extensions Preference pane. In fact it did not matter if I quit the black icon Xcode from within the app or if I pressed the stop button in the parent (blue icon) Xcode to kill it. The Extension always disappeared immediately. I also changed from debug to release mode. Still the same. 

So I have the feeling that this disappearing of the extension after testing it is considered to be a feature, not a bug. Assuming that it is a feature, there probably is a flag or install option somewhere in order to install final release versions of the extensions permanently.  Just, like you, I don't know where it is or how it is called (I'm afraid switching to release mode is not enough). 

The only way I currently know of to keep the extension permanently in the Extensions Preference Pane is to force quit the parent Xcode (blue icon) while the child Xcode (black icon) is still running. And this works every time.

Cheers ..

**Comment by mikeCalvir** [comment] 2016-10-14 10:17
I downloaded the app executable and ran it and chose a format file.
But Xcode source editor never shows up in my Extensions:

![screen shot 2016-10-14 at 12 13 37](https://cloud.githubusercontent.com/assets/340607/19384152/1d0b7e0e-9208-11e6-918d-915aba7646a3.png)

**Comment by hamaney** [comment] 2016-10-17 10:42
@jehnes  I tried it now but if I force stop the parent(blue icon Xcode) it kills the child (black icon Xcode) too. I cloned commit 3435481

**Comment by hamaney** [comment] 2016-10-17 10:44
@mikeCalvir it shows up temporarily as @jehnes was saying in the comment above urs, and that is one of the issue the dev is working on.

**Comment by goa** [comment] 2017-08-09 09:45
Hi, I had the same problem with Xcode 8 and Xcode 9 beta, but I managed to actually install and keep the extension present between Xcode restarts, by doing the following:

**a)** Make sure that both targets (XcodeClangFormat and clang-format) have a **Team** selected in **Signing**.

![1](https://user-images.githubusercontent.com/952620/29115193-6649cfd4-7cff-11e7-9502-64cc2865abae.jpg)

**b)** Instead of building the product, **Archive** it.

![2](https://user-images.githubusercontent.com/952620/29115248-a49c6ecc-7cff-11e7-81d9-10bc3960f7af.jpg)

**c)** Once the archive has been prepared, find it in finder, right click on it and **Show Package Contents**.

![3](https://user-images.githubusercontent.com/952620/29115316-e7d73e06-7cff-11e7-88ab-d54df23eca70.jpg)

**d)** Go to the Products/Applications folder and drag **XcodeClangFormat.app** to your Applications folder, then run it from there.

**e)** Open the **Settings** app and find **Extensions**. The Xcode Source Editor category should now be available and clang-format should be in there, even after Xcode and OS restarts.

![4](https://user-images.githubusercontent.com/952620/29115463-74fc440c-7d00-11e7-9ef0-0a13feefb26f.jpg)

**Comment by kkaefer** [comment] 2020-05-19 13:22
Looks like this doesn't occur anymore with newer versions of Xcode.

**Closed by kkaefer** 2020-05-19 13:22 UTC
